server:
  error:
    include-message: always
  port: 8084

spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/skymart_inventoryservice
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
